version: '1.0'
name: build-and-publish
displayName: 构建并发布
triggers:
  trigger: auto
  push:
    tags:
      include:
        - ^[0-9]+\.[0-9]+\.[0-9]+$
stages:
  - name: build
    displayName: 构建
    strategy: naturally
    trigger: auto
    executor:
      - jja8
    steps:
      - step: execute@docker
        name: gradle-build
        displayName: gradle构建
        certificate: ''
        image: gradle:8.2.1-jdk17-jammy
        command:
          - '## chmod +x ./gradlew'
          - gradle build
          - gradle shadow
        artifacts:
          - name: jars
            path:
              - '*/build/libs/*'
        notify: []
        strategy:
          retry: '0'
          timeout: 10
