version: '1.0'
name: build-and-publish
displayName: 构建并发布
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
stages:
  - name: build
    displayName: 构建
    strategy: naturally
    trigger: auto
    executor:
      - jja8
    steps:
      - step: execute@docker
        name: gradle-build
        displayName: gradle构建
        certificate: ''
        image: gradle:8.2.1-jdk17-jammy
        command:
          - '## chmod +x ./gradlew'
          - gradle bulidAllJar
        artifacts:
          - name: jars
            path:
              - './build/jars'
        notify: []
        strategy:
          retry: '0'
          timeout: 10
  - name: toup
    displayName: 上传作品
    strategy: naturally
    trigger: auto
    executor:
      - jja8
    steps:
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: jars
        artifactName: output
        notify: []
        strategy:
          retry: '0'
  - name: stage-3e42018f
    displayName: 发布
    strategy: naturally
    trigger: auto
    executor:
      - jja8
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 发布
        dependArtifact: output
        version: 1.0.0.0
        autoIncrement: true
        notify: []
        strategy:
          retry: '0'
